//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDPR.Utililty.Data
{
    using System;
    using System.Collections.Generic;

    public partial class GDPRSubjectPhone
    {
        public System.Guid PhoneId { get; set; }
        public System.Guid SubjectId { get; set; }
        public bool IsVerified { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string Raw { get; set; }
    }
}
